extensions: {}
cabal-file: project.cabal
version: 1
module-template: ! 'module MODULE_NAME where

'
modules:
  Rollbar:
    filename: src/Rollbar.hs
  Rollbar.MonadLogger:
    filename: src/Rollbar/MonadLogger.hs
