flags: {}
packages:
- '.'
- 'rollbar-haskell'
- location:
    git:    https://github.com/pbrisbin/yesod-paginator.git
    commit: 07958a8fe7e8730b57ca25b8a3b3d85d3377ca73
    
extra-deps:
- rollbar-0.3.1
- yesod-paginator-0.11
resolver: lts-8.12
