flags: {}
packages:
- '.'
- location:
    git:    https://github.com/jamesdabbs/yesod-paginator.git
    commit: eaeb101e14f6fd58cbec9e0d05d6acdf49a7d261

extra-deps:
- rollbar-0.3.1
- yesod-paginator-0.10
resolver: lts-3.3
