Default: &defaults
  user: ""
  password: ""
  host: localhost
  port: 5432
  database: brubeck_dev
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: brubeck_test
  <<: *defaults

Staging:
  database: brubeck_staging
  poolsize: 100
  <<: *defaults
