Default: &defaults
  user: pi_base
  password: pi_base
  host: localhost
  port: 5432
  database: pi_base_dev
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: pi_base_test
  <<: *defaults

Staging:
  database: pi_base_staging
  poolsize: 100
  <<: *defaults

Production:
  database: pi_base_production
  poolsize: 100
  <<: *defaults
