Default: &defaults
  user: pi-base
  password: pi-base
  host: localhost
  port: 5432
  database: pi-base
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: pi-base_test
  <<: *defaults

Staging:
  database: pi-base_staging
  poolsize: 100
  <<: *defaults

Production:
  database: pi-base_production
  poolsize: 100
  <<: *defaults
