Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: © James Dabbs 2012-2014
  analytics: UA-40474239-1

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  <<: *defaults
  approot: "http://topology.jdabbs.com"
